proxies:
  - name: 🇩🇪 Германия
    type: vless
    server: 91.107.189.143
    port: 29039
    uuid: 16c6faa4-1162-49ca-acf7-059afdf1ecd3
    udp: true
    network: tcp
  - name: 🇭🇰 Гонконг
    type: vmess
    server: 213.156.141.52
    port: 22324
    uuid: 04621bae-ab36-11ec-b909-0242ac120002
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇮🇳 Индия
    type: vmess
    server: 152.67.8.205
    port: 80
    uuid: 9db4c708-aef8-4359-821b-38e47990be0d
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: ''
      headers:
        Host: ''
  - name: 🏳️ Неизвестно
    type: vmess
    server: 216.238.86.158
    port: 34460
    uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
    alterId: 0
    cipher: auto
    udp: true
    network: none
  - name: 🇸🇬 Сингапур 1
    type: vmess
    server: 149.88.23.202
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 8
    type: vmess
    server: 38.114.123.42
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇯🇵 Япония
    type: vmess
    server: 172.104.80.66
    port: 22324
    uuid: 04621bae-ab36-11ec-b909-0242ac120002
    alterId: 1
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 4
    type: vmess
    server: 69.12.91.52
    port: 3593
    uuid: a3de462b-0276-4003-8f34-536b0f9d340c
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 12
    type: vmess
    server: 155.254.126.249
    port: 6001
    uuid: a030842a-d29a-4ea9-a776-14fc4b9e102d
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 1
    type: vmess
    server: 38.110.1.246
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 2
    type: vmess
    server: 129.146.143.80
    port: 48111
    uuid: d4603cc2-e0ee-4651-83f5-1db5b7168177
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇸🇬 Сингапур 2
    type: vless
    server: 47.82.239.48
    port: 43505
    uuid: 4cf81982-c8eb-4e7b-bd37-99cc5d49bc3c
    udp: true
    network: tcp
  - name: 🇯🇵 Япония 1
    type: vmess
    server: 153.121.73.175
    port: 32221
    uuid: b06054ae-f249-438e-998a-8e67bd8df653
    alterId: 0
    cipher: auto
    udp: true
    network: ''
  - name: 🇺🇸 США 6
    type: vmess
    server: 38.91.107.49
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇯🇵 Япония 3
    type: vmess
    server: 140.83.51.161
    port: 25686
    uuid: 6733c357-ba11-4e9f-f00f-7d87f2776ff9
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /cctv13.m3u8
      headers:
        Host: jp02.a0a.xyz
  - name: 🇺🇸 США 5
    type: vmess
    server: 67.220.85.46
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: aes-128-gcm
    udp: true
    network: tcp
  - name: 🏳️ Неизвестно 1
    type: vmess
    server: 47.250.149.51
    port: 50018
    uuid: 9665280c-a3d1-4aab-ef9f-a3a497337d91
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /9665280c
      headers:
        Host: 47.250.149.51
  - name: 🇭🇰 Гонконг 2
    type: vmess
    server: 47.238.130.197
    port: 443
    uuid: f267eac3-dfb4-45be-a480-7e1847ca04ab
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    tls: true
    ws-opts:
      path: /
      headers:
        Host: n1753348736.lie5d.cyou
  - name: 🇺🇸 США 10
    type: vmess
    server: 84.17.41.2
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇰🇷 Южная Корея
    type: vmess
    server: 146.56.112.110
    port: 8888
    uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США
    type: vmess
    server: 45.63.7.19
    port: 49632
    uuid: 05f2bbe3-f29a-480f-ebfb-0deebb80741d
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /05f2bbe3-f29a-480f-ebfb-0deebb80741d
      headers:
        Host: ''
  - name: 🇯🇵 Япония 2
    type: vmess
    server: 153.121.73.175
    port: 49803
    uuid: cd3dacbc-2b7b-4718-83ad-ab870f87e12e
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇮🇹 Италия
    type: vmess
    server: 45.92.70.236
    port: 22324
    uuid: 04621bae-ab36-11ec-b909-0242ac120002
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 9
    type: vmess
    server: 129.146.77.248
    port: 39495
    uuid: f836c736-87fc-4fde-aabc-00857ecdff3e
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /cctv13.m3u8
      headers:
        Host: 129.146.77.248
  - name: 🇪🇸 Испания
    type: vmess
    server: 85.90.217.42
    port: 22324
    uuid: 04621bae-ab36-11ec-b909-0242ac120002
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 11
    type: vmess
    server: 172.236.226.7
    port: 2053
    uuid: 95dd45fb-8e36-4ff2-fa9e-24b68a34f3cd
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    tls: true
    ws-opts:
      path: /usavm
      headers:
        Host: usaapp2.jisuyun.top
  - name: 🇩🇪 Германия 2
    type: vless
    server: 47.91.94.112
    port: 10040
    uuid: e4e7866d-920b-4a53-a8e2-6ae9b2a42fc2
    udp: true
    network: tcp
  - name: 🇩🇪 Германия 1
    type: vless
    server: 91.107.159.92
    port: 29810
    uuid: d114911d-4249-4aa3-b27b-c4f1989b34fd
    udp: true
    network: tcp
  - name: 🇺🇸 США 13
    type: vmess
    server: 172.236.244.171
    port: 2053
    uuid: 4b80aa86-4354-40bb-d2a3-47126cff0bea
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    tls: true
    servername: usaapp1.jisuyun.top
    ws-opts:
      path: /usavm
      headers:
        Host: usaapp1.jisuyun.top
  - name: 🇺🇸 США 7
    type: vmess
    server: 82.198.246.37
    port: 180
    uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇺🇸 США 3
    type: vmess
    server: 67.220.72.237
    port: 22324
    uuid: 04621bae-ab36-11ec-b909-0242ac120002
    alterId: 1
    cipher: auto
    udp: true
    network: tcp
  - name: 🇸🇬 Сингапур
    type: vmess
    server: 149.88.23.207
    port: 18000
    uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
    alterId: 0
    cipher: auto
    udp: true
    network: tcp
  - name: 🇭🇰 Гонконг 1
    type: vmess
    server: 47.76.254.70
    port: 443
    uuid: 6ea48dfe-7de2-45dc-9267-d4d9effad9fc
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    tls: true
    ws-opts:
      path: /
      headers:
        Host: n1753101277.4u9ma.icu
proxy-groups:
  - name: 🚀 Главный Выбор
    type: select
    proxies:
      - 🤖 Авто-режимы
      - 🌐 Все серверы (Ручной)
      - 🌍 Зарубеж (Ручной)
      - 🐻 Россия (Ручной)
      - DIRECT
  - name: 🤖 Авто-режимы
    type: select
    proxies:
      - ⚡ Лучший пинг (Все)
      - ⚡ Авто-Зарубеж
      - ⚡ Авто-Россия
  - name: 🌐 Все серверы (Ручной)
    type: select
    proxies:
      - 🇩🇪 Германия
      - 🇭🇰 Гонконг
      - 🇮🇳 Индия
      - 🏳️ Неизвестно
      - 🇸🇬 Сингапур 1
      - 🇺🇸 США 8
      - 🇯🇵 Япония
      - 🇺🇸 США 4
      - 🇺🇸 США 12
      - 🇺🇸 США 1
      - 🇺🇸 США 2
      - 🇸🇬 Сингапур 2
      - 🇯🇵 Япония 1
      - 🇺🇸 США 6
      - 🇯🇵 Япония 3
      - 🇺🇸 США 5
      - 🏳️ Неизвестно 1
      - 🇭🇰 Гонконг 2
      - 🇺🇸 США 10
      - 🇰🇷 Южная Корея
      - 🇺🇸 США
      - 🇯🇵 Япония 2
      - 🇮🇹 Италия
      - 🇺🇸 США 9
      - 🇪🇸 Испания
      - 🇺🇸 США 11
      - 🇩🇪 Германия 2
      - 🇩🇪 Германия 1
      - 🇺🇸 США 13
      - 🇺🇸 США 7
      - 🇺🇸 США 3
      - 🇸🇬 Сингапур
      - 🇭🇰 Гонконг 1
  - name: 🌍 Зарубеж (Ручной)
    type: select
    proxies:
      - 🇩🇪 Германия
      - 🇭🇰 Гонконг
      - 🇮🇳 Индия
      - 🏳️ Неизвестно
      - 🇸🇬 Сингапур 1
      - 🇺🇸 США 8
      - 🇯🇵 Япония
      - 🇺🇸 США 4
      - 🇺🇸 США 12
      - 🇺🇸 США 1
      - 🇺🇸 США 2
      - 🇸🇬 Сингапур 2
      - 🇯🇵 Япония 1
      - 🇺🇸 США 6
      - 🇯🇵 Япония 3
      - 🇺🇸 США 5
      - 🏳️ Неизвестно 1
      - 🇭🇰 Гонконг 2
      - 🇺🇸 США 10
      - 🇰🇷 Южная Корея
      - 🇺🇸 США
      - 🇯🇵 Япония 2
      - 🇮🇹 Италия
      - 🇺🇸 США 9
      - 🇪🇸 Испания
      - 🇺🇸 США 11
      - 🇩🇪 Германия 2
      - 🇩🇪 Германия 1
      - 🇺🇸 США 13
      - 🇺🇸 США 7
      - 🇺🇸 США 3
      - 🇸🇬 Сингапур
      - 🇭🇰 Гонконг 1
  - name: 🐻 Россия (Ручной)
    type: select
    proxies:
      - DIRECT
  - name: ⚡ Лучший пинг (Все)
    type: url-test
    hidden: true
    url: http://www.gstatic.com/generate_204
    interval: 150
    proxies:
      - 🇩🇪 Германия
      - 🇭🇰 Гонконг
      - 🇮🇳 Индия
      - 🏳️ Неизвестно
      - 🇸🇬 Сингапур 1
      - 🇺🇸 США 8
      - 🇯🇵 Япония
      - 🇺🇸 США 4
      - 🇺🇸 США 12
      - 🇺🇸 США 1
      - 🇺🇸 США 2
      - 🇸🇬 Сингапур 2
      - 🇯🇵 Япония 1
      - 🇺🇸 США 6
      - 🇯🇵 Япония 3
      - 🇺🇸 США 5
      - 🏳️ Неизвестно 1
      - 🇭🇰 Гонконг 2
      - 🇺🇸 США 10
      - 🇰🇷 Южная Корея
      - 🇺🇸 США
      - 🇯🇵 Япония 2
      - 🇮🇹 Италия
      - 🇺🇸 США 9
      - 🇪🇸 Испания
      - 🇺🇸 США 11
      - 🇩🇪 Германия 2
      - 🇩🇪 Германия 1
      - 🇺🇸 США 13
      - 🇺🇸 США 7
      - 🇺🇸 США 3
      - 🇸🇬 Сингапур
      - 🇭🇰 Гонконг 1
  - name: ⚡ Авто-Зарубеж
    type: url-test
    hidden: true
    url: http://www.gstatic.com/generate_204
    interval: 150
    proxies:
      - 🇩🇪 Германия
      - 🇭🇰 Гонконг
      - 🇮🇳 Индия
      - 🏳️ Неизвестно
      - 🇸🇬 Сингапур 1
      - 🇺🇸 США 8
      - 🇯🇵 Япония
      - 🇺🇸 США 4
      - 🇺🇸 США 12
      - 🇺🇸 США 1
      - 🇺🇸 США 2
      - 🇸🇬 Сингапур 2
      - 🇯🇵 Япония 1
      - 🇺🇸 США 6
      - 🇯🇵 Япония 3
      - 🇺🇸 США 5
      - 🏳️ Неизвестно 1
      - 🇭🇰 Гонконг 2
      - 🇺🇸 США 10
      - 🇰🇷 Южная Корея
      - 🇺🇸 США
      - 🇯🇵 Япония 2
      - 🇮🇹 Италия
      - 🇺🇸 США 9
      - 🇪🇸 Испания
      - 🇺🇸 США 11
      - 🇩🇪 Германия 2
      - 🇩🇪 Германия 1
      - 🇺🇸 США 13
      - 🇺🇸 США 7
      - 🇺🇸 США 3
      - 🇸🇬 Сингапур
      - 🇭🇰 Гонконг 1
  - name: ⚡ Авто-Россия
    type: url-test
    hidden: true
    url: http://www.gstatic.com/generate_204
    interval: 150
    proxies:
      - DIRECT
rules:
  - MATCH,🚀 Главный Выбор
