name: Collect Proxies

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'output/'
          message: 'Update proxies'
          push: true
